/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package de.saar.coli.dialogos.democlient;

import java.awt.Color;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.geom.AffineTransform;
import java.awt.image.AffineTransformOp;
import java.awt.image.BufferedImage;
import javax.swing.ImageIcon;
import javax.swing.SwingUtilities;

/**
 *
 * @author koller
 */
public class ClientFrame extends javax.swing.JFrame {

    private BufferedImage originalImage;
    private Image onImage;
    private Image offImage;

    public void setState(String state) {
        SwingUtilities.invokeLater(() -> {
            lState.setText(state);
            
            if( "CONNECTED".equals(state)) {
                lState.setForeground(Color.green);
            } else if( "CONNECTING".equals(state)) {
                lState.setForeground(Color.blue);
            } else if( "DISCONNECTED".equals(state)) {
                lState.setForeground(Color.red);
            }
        });
    }

    public void setLightState(boolean state) {
        SwingUtilities.invokeLater(() -> {
            if (state) {
                lImage.setIcon(new ImageIcon(onImage));
            } else {
                lImage.setIcon(new ImageIcon(offImage));
            }
        });
    }

    private static BufferedImage makeBuffered(Image image) {
        BufferedImage bimage = new BufferedImage(image.getWidth(null), image.getHeight(null), BufferedImage.TYPE_INT_ARGB);
        Graphics2D bGr = bimage.createGraphics();
        bGr.drawImage(image, 0, 0, null);
        bGr.dispose();
        
        return bimage;
    }
    
    /**
     * Creates new form ClientFrame
     */
    public ClientFrame(Image image) {
        super("Demo Client");
        
        this.originalImage = makeBuffered(image);
        
        offImage = originalImage.getSubimage(0, 0, 1200, 1812).getScaledInstance(200, -1, Image.SCALE_SMOOTH);
        onImage = originalImage.getSubimage(1200, 0, 1200, 1812).getScaledInstance(200, -1, Image.SCALE_SMOOTH);
        
        BufferedImage bOnImage = makeBuffered(onImage);
        
        AffineTransform tx = new AffineTransform();
        tx.translate(-4, 0);
        AffineTransformOp op = new AffineTransformOp(tx, AffineTransformOp.TYPE_BILINEAR);
        onImage = op.filter(bOnImage, (BufferedImage) null);

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lImage = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lState = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lImage.setToolTipText("");

        jLabel1.setText("State:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lImage, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lState, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lImage, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lState))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lImage;
    private javax.swing.JLabel lState;
    // End of variables declaration//GEN-END:variables
}
